image: "rust:latest"

default:
  before_script:
    - rustc --version
    - cargo --version

stages:
  - test

test-code:
  stage: test
  script:
    - cargo test
    - cargo install cargo-tarpaulin
    - cargo tarpaulin --ignore-tests
    - rustup component add clippy
    - cargo clippy -- -D warnings
    - rustup component add rustfmt
    - cargo fmt -- --check
    - cargo install cargo-audit
    - cargo audit
  only:
    - main

# lint-code:
#   stage: test
#   script:
#     - rustup component add clippy
#     - cargo clippy -- -D warnings
#
# format-code:
#   stage: test
#   script:
#     - rustup component add rustfmt
#     - cargo fmt -- --check
#
# audit-code:
#   stage: test
#   script:
#     - cargo install cargo-audit
#     - cargo audit
