[package]
name = "harddrive-party"
version = "0.1.0"
authors = ["peg <peg@magmacollective.org>"]
edition = "2021"
license = "GPL-3.0-or-later"
description = "Share files peer-to-peer"
homepage = "https://gitlab.com/pegpeg"
repository = "https://gitlab.com/pegpeg/harddrive-party"

[dependencies]
async-channel = "1.7.1"
futures-lite = "1.12.0"
prost = "0.11.2"
async-std = { version = "1.9.0", features = ["attributes", "unstable"] }
async-stream = "0.3.3"
futures-util = "0.3.25"
futures = "0.3.25"
async-walkdir = "0.2.0"
sled = "0.34.7"
thiserror = "1.0.37"

[dev-dependencies]
sluice = "0.5.5"
anyhow = "1.0.28"
tempfile = "3.3.0"

[build-dependencies]
prost-build = "0.11.2"
