[package]
name = "harddrive-party-shared"
description = "Shared types for harddrive-party and harddrive-party-web-ui"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
thiserror = "1.0.37"
serde = { version = "1.0", features = ["derive"] }
